import { html } from '@microsoft/fast-element';
import type { FoundationFormWithTabs } from './foundation-form-with-tabs';
import { ConnectedRenderersOptions, UiSchema } from '@genesislcap/foundation-forms';

// In the browser page, Click on "Copy autogenerated UI Schema".
// This button is only visible in the dev mode, when foundation-form attribute :uischema is not defined.
const UI_SCHEMA: UiSchema = {
  type: 'Categorization',
  elements: [
    {
      type: 'Control',
      scope: '#/properties/profiles',
      label: 'Profiles',
      options: {
        childElements: [
          {
            type: 'VerticalLayout',
            elements: [
              {
                type: 'Control',
                scope: '#/properties/USER_PROFILES',
                label: 'Profile',
                options: <ConnectedRenderersOptions>{
                  allOptionsResourceName: 'ALL_PROFILES',
                  valueField: 'PROFILE_NAME',
                  labelField: 'PROFILE_NAME',
                },
              },
              { type: 'Control', scope: '#/properties/ACCESS_TYPE' },
            ],
          },
        ],
      },
    },
    {
      type: 'Control',
      scope: '#/properties/information',
      label: 'Information',
      options: {
        childElements: [
          {
            type: 'LayoutVertical2Columns',
            elements: [
              { type: 'Control', scope: '#/properties/ADDRESS_LINE_1' },
              { type: 'Control', scope: '#/properties/ADDRESS_LINE_2' },
              { type: 'Control', scope: '#/properties/CITY' },
              { type: 'Control', scope: '#/properties/EMAIL_ADDRESS' },
            ],
          },
        ],
      },
    },
    {
      type: 'Control',
      scope: '#/properties/login',
      label: 'Login',
      options: {
        childElements: [
          {
            type: 'HorizontalLayout',
            elements: [
              { type: 'Control', scope: '#/properties/USER_NAME' },
              { type: 'Control', scope: '#/properties/USER_TYPE' },
              { type: 'Control', scope: '#/properties/LAST_LOGIN' },
            ],
          },
        ],
      },
    },
  ],
};

export const FoundationFormWithTabsTemplate = html<FoundationFormWithTabs>`
  <tutorial-container :route="${() => 'foundation-form-with-tabs'}">
    <zero-card>
      <foundation-form
        resourceName="EVENT_INSERT_USER"
        :uischema="${(x) => UI_SCHEMA}"
      ></foundation-form>
    </zero-card>
  </tutorial-container>
`;
